import { container } from '../application/di/container';
import { CreateUserDTO, User } from '../domain/entities/User';

export const usersAPI = {
  getById: async (id: number): Promise<User> => {
    return await container.getUserRepository().getById(id);
  },

  update: async (id: number, data: Partial<User>): Promise<User> => {
    return await container.getUserRepository().update(id, data);
  },

  getCurrentUser: async (): Promise<User> => {
    return await container.getUserRepository().getCurrent();
  },

  getAll: async (): Promise<User[]> => {
    return await container.getUserRepository().getAll();
  },

  // ID is generated by the backend
  create: async (data: Omit<CreateUserDTO , 'id'>): Promise<User> => {
    return await container.getUserRepository().create(data);
  },

  delete: async (id: number): Promise<void> => {
    return await container.getUserRepository().delete(id);
  },
};
